#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
DIRNAME="`dirname "$0"`"
GRADLE_HOME="$DIRNAME"
CLASSPATH=$GRADLE_HOME/gradle/wrapper/gradle-wrapper.jar

determineOs() {
    case "`uname`" in
        Darwin*)
            OS_NAME="macos"
            ;;
        Linux*)
            OS_NAME="linux"
            ;;
        *)
            OS_NAME="unknown"
            ;;
    esac
}

determineJava() {
    if [ -n "$JAVA_HOME" ]; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        JAVACMD="java"
    fi
}

determineOs
determineJava

exec "$JAVACMD" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
